#!/usr/bin/env python3
"""Turn the OSD's BDF font into a C header of packed glyph rows.

    tools/makefont.py <out.h> <font.bdf>

Generated rather than committed: the BDF is the input a reader needs to
reproduce the table, and a checked-in copy of the table would be a second
place for the same bytes to drift. Like `makestamp.py`, the file is rewritten
only when its contents change, so an unchanged font costs no rebuild.

Only the printable ASCII range is emitted. Every string the OSD draws is the
project's own and is written in ASCII, so the rest of the face is weight the
image does not need.

The generator refuses a font whose glyphs are not all the bounding box's size.
The blit that consumes this table indexes it as a flat grid, so a single
narrow glyph would silently shear every row after it rather than fail.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

# Printable ASCII, space through tilde.
FIRST = 0x20
LAST = 0x7E


class FontError(Exception):
    """The BDF is not the shape the blit assumes."""


def shape(box: tuple[int, int, int, int]) -> str:
    return f"{box[0]} {box[1]} {box[2]} {box[3]}"


def parseBdf(text: str) -> tuple[int, int, dict[int, list[int]]]:
    """Return (width, height, {codepoint: rows}) for the whole font.

    Each row is one byte, MSB the leftmost pixel, which is how BDF already
    stores it for any face up to eight pixels wide.
    """
    # All four BBX fields, offsets included: a glyph shifted inside the cell
    # is as wrong for a flat table as one of the wrong size, and nothing
    # downstream would notice a row of displacement.
    box: tuple[int, int, int, int] | None = None
    glyphs: dict[int, list[int]] = {}

    encoding: int | None = None
    size: tuple[int, int, int, int] | None = None
    advance: int | None = None
    rows: list[int] | None = None

    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if rows is not None:
            if line == "ENDCHAR":
                if encoding is None or size is None or advance is None:
                    raise FontError(f"line {number}: a glyph missing its "
                                    "ENCODING, BBX or DWIDTH")
                if size != box:
                    raise FontError(
                        f"line {number}: glyph {encoding} has BBX {shape(size)}, "
                        f"not the bounding box's {shape(box)}")
                if advance != size[0]:
                    raise FontError(
                        f"line {number}: glyph {encoding} advances {advance}, not "
                        f"the {size[0]} it occupies; the face is not monospaced")
                if len(rows) != size[1]:
                    raise FontError(
                        f"line {number}: glyph {encoding} has {len(rows)} rows, "
                        f"not {size[1]}")
                glyphs[encoding] = rows
                encoding, size, advance, rows = None, None, None, None
            else:
                # One or more bytes per row; a face this narrow uses one, and
                # taking only the first keeps the width assertion the thing
                # that rejects a wider font rather than a silent truncation.
                if len(line) != 2:
                    raise FontError(f"line {number}: {len(line) * 4} bits of bitmap, "
                                    "expected 8")
                rows.append(int(line, 16))
            continue

        if line.startswith("FONTBOUNDINGBOX "):
            box = tuple(int(f) for f in line.split()[1:5])
        elif line.startswith("ENCODING "):
            encoding = int(line.split()[1])
        elif line.startswith("BBX "):
            size = tuple(int(f) for f in line.split()[1:5])
        elif line.startswith("DWIDTH "):
            advance = int(line.split()[1])
        elif line == "BITMAP":
            if box is None:
                raise FontError(f"line {number}: a glyph before FONTBOUNDINGBOX")
            rows = []

    if box is None:
        raise FontError("no FONTBOUNDINGBOX")
    if box[0] > 8:
        raise FontError(f"the font is {box[0]} pixels wide; a row no longer "
                        "packs into one byte")
    return box[0], box[1], glyphs


def render(width: int, height: int, glyphs: dict[int, list[int]],
           source: str) -> str:
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        names = ", ".join(f"0x{c:02X}" for c in missing[:8])
        plural = "" if len(missing) == 1 else "s"
        raise FontError(f"{len(missing)} printable character{plural} not in the "
                        f"font: {names}")

    count = LAST - FIRST + 1
    out = [
        f"// Generated by tools/makefont.py from {source}. Do not edit.",
        "//",
        "// M+ BITMAP FONTS, Copyright 2002-2005 COZ <coz@users.sourceforge.jp>.",
        "// Unlimited permission is granted to use, copy, and distribute it,",
        "// with or without modification, either commercially and",
        "// noncommercially. Provided as is, without warranty. Provenance and",
        "// the licence text are under licenses/mplus.",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "namespace ps2::font {",
        "",
        f"inline constexpr uint32_t kGlyphWidth = {width};",
        f"inline constexpr uint32_t kGlyphHeight = {height};",
        f"inline constexpr uint32_t kFirstGlyph = 0x{FIRST:02X};",
        f"inline constexpr uint32_t kGlyphCount = {count};",
        "",
        f"// {count} glyphs of {height} rows, one byte each, the leftmost pixel",
        "// in bit 7. A character's rows start at",
        "// `(c - kFirstGlyph) * kGlyphHeight`.",
        "inline constexpr uint8_t kGlyphRows[kGlyphCount * kGlyphHeight] = {",
    ]

    for code in range(FIRST, LAST + 1):
        packed = ", ".join(f"0x{row:02X}" for row in glyphs[code])
        # Quoted, and the backslash doubled: a bare one at the end of a `//`
        # line splices the next line into the comment.
        label = chr(code).replace("\\", "\\\\")
        out.append(f"    {packed},  // '{label}'")

    out += [
        "};",
        "",
        "}  // namespace ps2::font",
        "",
    ]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("out", type=pathlib.Path)
    parser.add_argument("bdf", type=pathlib.Path)
    # The comment in the header names the font by its place in the tree, not by
    # the path the build happened to pass in: nothing about where the tree
    # lives goes into the image.
    parser.add_argument("--name", default="third_party/fonts/mplus_f12r.bdf",
                        help="what to call the font in the generated comment")
    args = parser.parse_args()

    try:
        width, height, glyphs = parseBdf(args.bdf.read_text(encoding="latin-1"))
        text = render(width, height, glyphs, args.name)
    except FontError as error:
        print(f"{args.bdf}: {error}", file=sys.stderr)
        raise SystemExit(1)

    if args.out.exists() and args.out.read_text() == text:
        return
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)


if __name__ == "__main__":
    main()
