#!/usr/bin/env python3
"""Write the header that says which commit the image is built from.

OSDSYS prints the stamp, so it has to be true at the moment of the build,
not at the moment of the last `cmake` run: a configure-time value goes stale
the first time the tree moves on. Run on every build; the file is rewritten
only when its contents change, so an unchanged commit costs no rebuild.

    tools/makestamp.py <out.h> <source-dir>

The header carries the commit only. Nothing about where the tree lives goes
into the image.
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess

UNKNOWN = "unknown"


def git(source: pathlib.Path, *args: str) -> str | None:
    try:
        result = subprocess.run(["git", "-C", str(source), *args],
                                capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def stamp(source: pathlib.Path) -> str:
    short = git(source, "rev-parse", "--short", "HEAD")
    if not short:
        # A tarball, or a tree with no commit yet: the image still builds and
        # the line still says something.
        return UNKNOWN
    # A dirty tree is not the commit it names, and one character says so.
    if git(source, "status", "--porcelain", "--untracked-files=no"):
        short += "+"
    return short


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("out", type=pathlib.Path)
    parser.add_argument("source", type=pathlib.Path)
    args = parser.parse_args()

    text = ("// Generated by tools/makestamp.py on every build. Do not edit.\n"
            "#pragma once\n"
            f'#define PS2_BUILD_STAMP "{stamp(args.source)}"\n')

    if args.out.exists() and args.out.read_text() == text:
        return
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)


if __name__ == "__main__":
    main()
